services:
  tor_with_bridges:
    image: deathmond1987/tor_with_bridges:latest
    container_name: tor
    hostname: tor
    restart: always
    ports:
      - "9050:${SOCKS_PORT}"
      - "9051:${TOR_CONTROL_PORT}"
    env_file:
      - .env
