services:
  tor_with_bridges:
    image: deathmond1987/tor_with_bridges:latest
    container_name: tor_with_bridges
    hostname: tor_with_bridges
    restart: always
    environment:
      - "SOCKS_IP=0.0.0.0"
      - "SOCKS_PORT=9050"
      - "EXIT_RELAY=0"
      - "NUM_RELAYS=100"
      - "MIN_RELAYS=2"
      - "RELAY_TIMEOUT=3"
## set proxy for download list of bridges. Format: http://user:pass@host:port; socks5h://user:pass@host:port'
      - "PROXY_FOR_SCANNER="
      - "HTTPS_PROXY="
      - "HTTPS_PROXY_CREDS="
      - "SOCKS_ACCEPT="
      - "SOCKS_REJECT="
      - "PROXY_FOR_SCANNER"
