name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tor_build_container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN 
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag deathmond1987/tor_with_bridges:latest
      
    - name: Docker Push
      run: docker push deathmond1987/tor_with_bridges:latest
